### ISSUE TITLE
Continuously throwing java.lang.InterruptedException to syslog fills disk after some minutes

### ISSUE THREAD

**Issue by helderdaniel** [argouml-tigris-org/argouml#67]
Running in Ubuntu 22.04, it keeps issuing **java.lang.InterruptedException**
Moreover it logs all in system log (/var/log/syslog)  filling the disk up to 100% after some minutes.

```
INFORMATIONAL *********** Exception occurred ************ at Tue Aug 29 11:52:28 WEST 2023
java.lang.InterruptedException
	at org.openide.util.Utilities$ActiveQueue.remove(Utilities.java:2940)
	at java.base/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:214)
	at org.openide.util.Utilities$ActiveQueue.run(Utilities.java:2957)
	at java.base/java.lang.Thread.run(Thread.java:1589)
INFORMATIONAL *********** Exception occurred ************ at Tue Aug 29 11:52:28 WEST 2023
java.lang.InterruptedException
	at org.openide.util.Utilities$ActiveQueue.remove(Utilities.java:2940)
	at java.base/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:214)
	at org.openide.util.Utilities$ActiveQueue.run(Utilities.java:2957)
	at java.base/java.lang.Thread.run(Thread.java:1589)
INFORMATIONAL *********** Exception occurred ************ at Tue Aug 29 11:52:28 WEST 2023
```

**Comment by linustolke** [comment]
This is strange. I don't understand where the org.openide comes from. Could you provide some more details on how you have built and started the system or what version of ArgoUML you are using?

**Comment by avysk** [comment]
I have the same issue in FreeBSD 15-CURRENT with ArgoUML 0.34.

```
java.lang.InterruptedException
        at org.openide.util.Utilities$ActiveQueue.remove(Utilities.java:2940)
        at java.base/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:225)
        at org.openide.util.Utilities$ActiveQueue.run(Utilities.java:2957)
        at java.base/java.lang.Thread.run(Thread.java:1575)
`````

**Comment by avysk** [comment]
Ok, the problem bypassed. I have OpenJDK 23 installed, so `java` with which `argouml.jar` is run is actually version 23. Manually running with `/usr/local/openjdk8/jre/bin/java` eliminated the problem.

**Comment by VVD** [comment]
This behavior begins with OpenJDK 19.
Work fine with 18 and early.

**Comment by VVD** [comment]
openide-util.jar in Argouml is from 2005.
I can't find sources of org.openide.util.Utilities from that time.
Probably update of the openide-util.jar can help.

I don't want decompile it, add something like:
```java
     try {
// code which throw InterruptedException
     } catch (InterruptedException e) {
         Thread.currentThread().interrupt();
     }
```
compile and replace it in openide-util.jar with removed signatures…
:-D
